---
- hosts: {{ my_hosts }}
  gather_facts: no
  connection: local
 
  tasks:
  - name: Execute "write mem" on device
    ios_command:
      commands:
        - wr mem 
    register: write
 
  - debug: var=write.stdout_lines
