---
- hosts: "{{ my_hosts }}"
  gather_facts: no
  connection: local

  tasks:
  - name: Setting ISIS overload timeout
    junos_config:
      lines: 
        - set protocols isis overload timeout 300
        - set protocols isis overload advertise-high-metrics
    register: result

  - name: print result
    debug: var=result
