---
- hosts: "{{ my_hosts }}"
  gather_facts: no
  connection: local

  tasks:
  - name: Setting ISIS overload - JUNOS
    junos_config:
      lines: 
        - delete protocols isis overload timeout
        - delete protocols isis interface lo0.0 metric
        - delete protocols isis interface lo0.0 ipv6-unicast-metric
        - set protocols isis overload advertise-high-metrics
    when: ansible_network_os == "junos"

