---
- hosts: "{{ my_hosts }}"
  gather_facts: no
  connection: local

  tasks:
  - name: Removing ISIS Overload - JUNOS
    junos_config:
      lines: 
        - set protocols isis overload timeout 300
        - set protocols isis overload advertise-high-metrics
        - delete protocols isis interface lo0.0 level 2 metric
        - delete protocols isis interface lo0.0 level 2 ipv6-unicast-metric
    when: ansible_network_os == "junos"
