---
- name: Get Device Facts 
  hosts: {{ my_hosts }}
  roles:
  - juniper.junos
  connection: local
  gather_facts: no

  tasks:
  - name: Retrieve information from devices running Junos OS
    junos_get_facts: 
    register: junos

  - name: Show Version
    debug: msg="{{ junos.facts.version }}"
