---
- name: Get Device Facts 
  hosts: juniper
  roles:
  - juniper.junos
  connection: local
  gather_facts: no

  tasks:   
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port={{ PORT_NETCONF }} timeout=5

  - name: Retrieve information from devices running Junos OS
    junos_get_facts: 
    register: junos

#  - name: Show Version
#    debug: msg="{{ junos.facts.version }}"
